apiVersion: v1
kind: Pod
metadata:
  name: simple-color-config
  labels:
    app: simple-color
spec:
  containers:
    - image: mmumshad/simple-webapp-color
      name: simple-color
      # env config at container-level specification
      env:
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: simple-color-configmap
              key: COLOR_ENV
      ports:
        - containerPort: 8080
          protocol: TCP
