apiVersion: v1
kind: Service
metadata:
  name: simple-color-nport
  labels:
    app: simple-color
spec:
  type: NodePort
  ports:
    # port 80 is default when "targetPort" is not specified
    - port: 80
      targetPort: 8080
      nodePort: 30100
  selector:
    app: simple-color
