apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: frontend
spec:
  type: LoadBalancer
  # Port 80 is default when "targetPort" is not specified
  ports:
    - port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: frontend
