apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-local-pvc
  labels:
    type: local
spec:
  storageClassName: localstorage
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/mongodb
